name: Google Finance POM Tests

on:
  # nightly at 00:00 America/Los_Angeles = 07:00 UTC
  schedule:
    - cron:  '0 7 * * *'
  workflow_dispatch:
    inputs:
      test:
        description: 'Which spec to run'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - missing
          - unexpected

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      # Run all tests on schedule or when "all" is chosen
      - name: Run all finance tests
        if: >
          github.event_name == 'schedule' ||
          github.event.inputs.test == 'all'
        run: npx cypress run --spec "cypress/e2e/finance.cy.js"

      # Run only the "missing symbols" spec
      - name: Run missing-symbols test
        if: github.event.inputs.test == 'missing'
        run: npx cypress run --spec "cypress/e2e/finance-missing.cy.js"

      # Run only the "unexpected symbols" spec
      - name: Run unexpected-symbols test
        if: github.event.inputs.test == 'unexpected'
        run: npx cypress run --spec "cypress/e2e/finance-unexpected.cy.js"
